import { Open_Sans } from 'next/font/google';

export const LANGUAGES = [
  {
    alias: 'en',
    name: 'English',
  },
  {
    alias: 'vn',
    name: 'Tiếng Việt',
  },
  {
    alias: 'br',
    name: 'Brazil',
  },
  {
    alias: 'ID',
    name: 'Indonesia',
  },
];

export const REGEX_LINK_TIKTOK = [
  /^(https?:\/\/)?(www\.)?(tiktok\.com\/(@\w+\/)?video\/(\d+)|vm\.tiktok\.com\/([\w-]+))$/,
  /^https?:\/\/(?:www\.)?tiktok\.com\/@(?:[\w-]+\.)+[\w-]+\/video\/(\d{19})/,
  /(?:http(?:s)?:\/\/)?(?:www\.)?(?:tiktok\.com\/(?:@\w+\/)?video\/\d{19})/,
  /(?:http(?:s)?:\/\/)?(?:www\.)?(?:tiktok\.com\/(?:\w{2}\/)?@[\w\.\d-]+\/video\/\d{19})/,
  /(?:http(?:s)?:\/\/)?(?:www\.)?(?:tiktok\.com\/v\/\d{19})/,
  /^https?:\/\/(?:www\.)?tiktok\.com\/@[a-zA-Z0-9_.-]+\/video\/(\d{19,99})/,
];

export const REGEX_LINK_DOUYIN =
  /^(https?:\/\/)?(www\.)?(douyin\.com\/(@\w+\/)?\w+\/\w+\/\w+\/\w+\/(\w+)|v\.douyin\.com\/\w+\/\w+\/\w+\/\w+\/(\w+))$/;

export const openSans = Open_Sans({
  subsets: ['latin'],
  weight: '400',
});

export const keywords = [
  'video tiktok',
  'tải video tiktok',
  'tai video tiktok',
  'TikTok video downloader',
  'TikTok downloader',
  'TikTok video download without watermark',
  'Download TikTok videos',
  'Free TikTok video downloader',
  'Download TikTok videos online',
  'TikTok video saver',
  'Download TikTok videos without watermark',
  'TikTok video downloader app',
  'TikTok video downloader online',
  'Download TikTok videos in high quality',
  'TikTok video download link',
  'Download TikTok videos with sound',
  'TikTok video download for free',
  'Save TikTok videos',
  'Download TikTok videos to camera roll',
  'Download TikTok videos on Android/iOS',
  'Download TikTok videos on PC',
  'TikTok video downloader Chrome extension',
  'How to download TikTok videos',
  'TikTok video download tutorial',
  'TikTok video downloader for Mac',
  'download video tiktok',
  'video tiktok no logo, watermark',
  'tai video tiktok khong logo, watermark',
  'tải video tiktok không logo',
  'tải video tiktok không watermark',
  'TikTok downloader',
  'TikTok video downloader',
  'download TikTok videos without watermark',
  'tải video TikTok',
  'tải video TikTok miễn phí',
  'tai video tiktok mien phi',
  'tải video TikTok không watermark',
  'tai video TikTok khong watermark',
  'tải video TikTok nhanh nhất',
  'tai video TikTok nhanh nhat',
  'tải video TikTok trực tuyến',
  'tai video TikTok truc tuyen',
  'tải video TikTok online',
  'tai video TikTok online',
  'tải video TikTok về điện thoại',
  'tai video TikTok ve dien thoai',
  'tải video TikTok về máy tính',
  'tai video TikTok ve may tinh',
  'tải video TikTok HD',
  'tai video TikTok HD',
  'tải video TikTok 4K',
  'tai video TikTok 4K',
  'tải video TikTok private',
  'tai video TikTok private',
  'tải video TikTok không cần đăng nhập',
  'tai video TikTok khong can đang nhap',
  'tải video TikTok đơn giản',
  'tai video TikTok đon gian',
  'tải video TikTok dễ dàng',
  'tai video TikTok de dang',
  'baixar vídeo tiktok',
  'download de vídeos tiktok',
  'como baixar vídeo tiktok',
  'como fazer download de vídeos tiktok',
  'tiktok downloader',
  "baixar tiktok sem marca d'água",
  "como baixar tiktok sem marca d'água",
  'baixar tiktok grátis',
  'baixar tiktok para celular',
  'tiktok download gratuito',
  'unduh video tiktok',
  'download video tiktok',
  'simpan video tiktok',
  'ambil video tiktok',
  'dapatkan video tiktok',
  'unduh video tiktok tanpa watermark',
  'cara download video tiktok',
  'download video tiktok gratis',
  'download video tiktok hd',
  'download video tiktok online',
  'download video tiktok mp4',
  'download video tiktok ke galeri',
  'unduh video tiktok cepat',
  'aplikasi download video tiktok',
  'website download video tiktok',
  'unduh video tiktok terbaru',
  'unduh video tiktok viral',
];
